name: Golang Unit Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GO111MODULE: off

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'

      - name: run tests with coverage
        run: go test -coverprofile=coverage.out ./...

      - name: collect coverage artifacts
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.out
          flags: unittests

      - name: update statistics
        run: go run stat.go

      - uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'update statistics'
          files: 'README.md'
          name: github-actions
          email: noreply@github.com
